### ISSUE TITLE
wot working on windows

### ISSUE THREAD

**Issue by SolidSoftwareServices** [roryprimrose/rungitversion#8]
Not working when 
```
... 
 runs-on: windows-latest
...
```
output: 
Run roryprimrose/rungitversion@v1
  with:
    nofetch: false
    nocache: false
  env:
    working-directory: ./tools/NavigationPrototype/
    solutionFile: S3.NavigationPrototype.sln
    testResultsDirectory: ./TestResults/
**Error: Container action is only supported on Linux**

**Comment by roryprimrose** [comment]
You will need to take this up with Github as it is a platform restriction. 

I recommend you use the official GitVersion action as it has since been released.
